/**
 * Created by zhoufan on 2015/8/15.
 */
/**
 * 事件类型定义
 */
var SyEvent = {
    SOCKET_OPENED:"SOCKET_OPENED",
    SOCKET_CLOSED:"SOCKET_CLOSED",
    DIRECT_JOIN_ROOM:"DIRECT_JOIN_ROOM",

    CARD_TOUCHED:1,

    JOIN_ROOM:"JOIN_ROOM",
    EXIT_ROOM:"EXIT_ROOM",
    PLAYER_PRO_UPDATE:"PLAYER_PRO_UPDATE",
    PLAYER_STATUS_CHANGE:"PLAYER_STATUS_CHANGE",
    START_PLAY:"START_PLAY",
    LET_OUT_CARD:"LET_OUT_CARD",
    GET_MAJIANG:"GET_MAJIANG",
    CS_GANG_MAJIANG:"CS_GANG_MAJIANG",
    CS_HAIDI:"CS_HAIDI",
    AH_GANG_MAJIANG:"AH_GANG_MAJIANG",
    SELECT_MAJIANG:"SELECT_MAJIANG",
    ONLINE_OFFLINE_NOTIFY:"ONLINE_OFFLINE_NOTIFY",
    SETTLEMENT_SUCCESS:"SETTLEMENT_SUCCESS",
    OVER_PLAY:"OVER_PLAY",
    ROOM_FAST_CHAT:"ROOM_FAST_CHAT",
    LUCKDRAW_TURNNMU:"LUCKDRAW_TURNNMU",
    LUCKDRAW_AWARD:"LUCKDRAW_AWARD",
    USER_AUDIO_READY:"USER_AUDIO_READY",
    USER_AUDIO_PLAY_START:"USER_AUDIO_PLAY_START",
    USER_AUDIO_PLAY_FINISH:"USER_AUDIO_PLAY_FINISH",
    DOUNIU_STATUS_UPDATE:"DOUNIU_STATUS_UPDATE",
    DOUNIU_ZHUANG_RECEIVE:"DOUNIU_ZHUANG_RECEIVE",
    DOUNIU_QI_ZHUANG:"DOUNIU_QI_ZHUANG",
    DOUNIU_XIA_ZHU:"DOUNIU_XIA_ZHU",
    DOUNIU_DECIDE_ZHUANG:"DOUNIU_DECIDE_ZHUANG",
    DOUNIU_LIANG_PAI:"DOUNIU_LIANG_PAI",
    DOUNIU_SELECT_CARD:"DOUNIU_SELECT_CARD",
    DOUNIU_INTERACTIVE_PROP:"DOUNIU_INTERACTIVE_PROP",
    DTZ_UPDATE_GPS:"DTZ_UPDATE_GPS",
    ROOM_ROLD_ICON:"ROOM_ROLD_ICON",

    //PHZ
    FANGZHAO:"FANGZHAO",
    FIX_OUT_CARD:"FIX_OUT_CARD",
    PHZ_HIDE_ACTION:"PHZ_HIDE_ACTION",
    PHZ_DEAL_CARD:"PHZ_DEAL_CARD",
    PHZ_CLEAN_TING:"PHZ_CLEAN_TING",
    PHZ_HIDE_TING:"PHZ_HIDE_TING",


    //
    NEW_TIPS:"NEW_TIPS",
    UPDATE_TIME:"UPDATE_TIME",
    UPDATE_WAITING:"UPDATE_WAITING",
    UPDATE_MATCH:"UPDATE_MATCH",
    MATCH_INVITE:"MATCH_INVITE",
    MATCH_START:"MATCH_START",
    ID_VDRIFY:"ID_VDRIFY",
    //比赛场
    MATCH_REGISTRY:"MATCH_REGISTRY",
    //战绩分享消息
    RECORD_SHARE:"RECORD_SHARE",
    //清除解散房间框
    DISAGREE_APPLYEXITROOM:"DISAGREE_APPLYEXITROOM",
    BBT_STATUS_UPDATE:"BBT_STATUS_UPDATE",
    BBT_CHUI:"BBT_CHUI",
    SHOW_CHUi:"SHOW_CHUi",
    SHOW_KAIQIANG:"SHOW_KAIQIANG",
    SHOW_ROBBER:"SHOW_ROBBER",
    SHOW_TU:"SHOW_TU",
    BBT_DECIDE_ZHUANG:"BBT_DECIDE_ZHUANG",
    SHOW_SCORE:"SHOW_SCORE",
    CLEAN_CURLUN:"CLEAN_CURLUN",
    //代开刷新
    DAIKAI_REFRESH:"DAIKAI_REFRESH",

    //错误提示
    GET_SERVER_SUC:"GET_SERVER_SUC",
    NOGET_SERVER_ERR:"NOGET_SERVER_ERR",

    //军团
    RFRSH_CY_LIST:"RFRSH_CY_LIST",
    FIX_JT_CHENYUAN:"FIX_JT_CHENYUAN",
    DELETE_JT_CHENYUAN:"DELETE_JT_CHENYUAN",
    FIX_JT_PAIJU:"FIX_JT_PAIJU",
    FIX_JT_ALL_PAIJU:"FIX_JT_ALL_PAIJU",
    UPDATE_XZ_PJ:"UPDATE_XZ_PJ",
    ADD_JT_PAIJU:"ADD_JT_PAIJU",
    UPDATE_ALL_SLECT_PJ:"UPDATE_ALL_SLECT_PJ",
    UPDATE_RENS_MAN:"UPDATE_RENS_MAN",
    DOUNIU_WATCHER_JOINED:"DOUNIU_WATCHER_JOINED",
    JOIN_JT_PANEL:"JOIN_JT_PANEL",
    CREATE_CLUB_OK:"CREATE_CLUB_OK",
    SEND_JOIN_CLUB_OK:"SEND_JOIN_CLUB_OK",
    JOIN_CLUB_OK:"JOIN_CLUB_OK",
    UPDATE_CLUB_LIST:"UPDATE_CLUB_LIST",
    OPEN_BYQ_PANEL:"OPEN_BYQ_PANEL",
    ZYJT_QIE_FU:"ZYJT_QIE_FU",
    MEJT_QIE_FU:"MEJT_QIE_FU",
    DELETE_JT_PAIJU:"DELETE_JT_PAIJU",
    RFRSH_DELETE_LIST:"RFRSH_DELETE_LIST",
    TUICHU_ZQ_ROOM:"TUICHU_ZQ_ROOM",
    OPEN_XG_CY:"OPEN_XG_CY",
    OPEN_SHENPI_PANEL:"OPEN_SHENPI_PANEL",
    ZYJT_ZQ_QIE_FU:"ZYJT_ZQ_QIE_FU",
    ZYJT_JT_QIE_FU:"ZYJT_JT_QIE_FU",
    DOUNIU_TD_PLAYER:"DOUNIU_TD_PLAYER",
    DOUNIU_UPDATE_XYF:"DOUNIU_UPDATE_XYF",
    DELETE_CUOPAI_LAYER:"DELETE_CUOPAI_LAYER",
    UPDATE_BG_YANSE:"UPDATE_BG_YANSE",
    UPDATE_TUOGUAN:"UPDATE_TUOGUAN",
    UPDATE_PB_YANSE:"UPDATE_PB_YANSE",
    UPDATE_YL_LEIX:"UPDATE_YL_LEIX",
    STOP_ALL_QZANIM:"STOP_ALL_QZANIM",
    CLAN_ALL_XIAZHU:"CLAN_ALL_XIAZHU",
    GET_JT_PAIJU:"GET_JT_PAIJU",
    QIANDAO:"QIANDAO",
    OPEN_ACTIVE:"OPEN_ACTIVE",
    SHOW_WANG:"SHOW_WANG",
    SHOW_HTTHREE:"SHOW_HTTHREE",
    REFRESH_CREATE_ROOM_BTN:"REFRESH_CREATE_ROOM_BTN",
    UPDATE_JLB:"UPDATE_JLB",
    DTZ_DEAL_SCORE:"DTZ_DEAL_SCORE",
    GOTO_MONEY_HOME:"GOTO_MONEY_HOME",
    GET_MONEYTODIAMOND_ITEMS:"GET_MONEY_ITEMS",
    GET_DIAMONDTOMONEY_ITEMS:"GET_DIAMONDTOMONEY_ITEMS",
    BUY_MONEY_ITEMS:"BUY_MONEY_ITEMS",
    BUY_DIAMOND_ITEM:"BUY_DIAMOND_ITEM",
    BIND_INVITECODE_SUC:"BIND_INVITECODE_SUC",
    REMOVE_MONEY_LOADING:"REMOVE_MONEY_LOADING",
    REMOVE_MATCH_LOADING:"REMOVE_MATCH_LOADING",
    GET_MONEY_CONFIG:"GET_MONEY_CONFIG",//获取金币场配置
    CLUB_DELETE_ONE:"CLUB_DELETE_ONE",//解散俱乐部房间
    GET_CLUB_ROOMS:"GET_CLUB_ROOMS",//刷新俱乐部房间信息
    CLUB_ROOM_DETAILPOP:"CLUB_ROOM_DETAILPOP",//获取俱乐部房间信息
    RESET_TIME:"RESET_TIME",//重新选择时间区间
    CLUB_DELETE_TEAM_SUC:"CLUB_DELETE_TEAM_SUC",//删除俱乐部分组成功
    CLUB_CREATE_TEAM_SUC:"CLUB_CREATE_TEAM_SUC",//创建俱乐部分组成功
    UPDATE_CLUB_MEMBER_NUMBER:"UPDATE_CLUB_MEMBER_NUMBER",        //俱乐部分组人员发生变动
    OPEN_TEAM_DETAIL:"OPEN_TEAM_DETAIL",//点击某条俱乐部分组 打开分组详情界面
    UPDATE_CLUB_CHOOSE_PANEL:"UPDATE_CLUB_CHOOSE_PANEL", //刷新显示操作层
    GET_CLUB_BAGS:"GET_CLUB_BAGS",//获取俱乐部的包厢
    GET_CLUB_ALLBAGS:"GET_CLUB_ALLBAGS",//获取所有包厢的信息
    UPDATE_CLUB_BAGS:"UPDATE_CLUB_BAGS",//刷新所有包厢的信息
    CLOSE_CLUB_BAGS:"CLOSE_CLUB_BAGS",//关闭包厢管理

    UPDATE_SET_KSCP:"UPDATE_SET_KSCP",
    UPDATE_SET_KQTP:"UPDATE_SET_KQTP",
    UPDATE_SET_YYXZ:"UPDATE_SET_YYXZ",
    UPDATE_SET_CPSD:"UPDATE_SET_CPSD",
    UPDATE_SET_ZPDX:"UPDATE_SET_ZPDX",
    UPDATE_SET_XXXZ:"UPDATE_SET_XXXZ",
    UPDATE_SET_ZPXZ:"UPDATE_SET_ZPXZ",

    CLUB_SHOW_MATCH_TIP:"CLUB_SHOW_MATCH_TIP", //俱乐部快速匹配提示

    MATCH_ALL_GAMES:"MATCH_ALL_GAMES",//显示比赛场所有场次
    MATCH_APPLY_DETAIL:"MATCH_APPLY_DETAIL",//显示比赛场报名详情
    MATCH_REFRESH_RENSHU:"MATCH_REFRESH_RENSHU",//刷新报名人数
    MATCH_REFRESH_RANK:"MATCH_REFRESH_RANK",//刷新比赛排名
    MATCH_SHOW_TIP:"MATCH_SHOW_TIP",//控制是否显示提示
    MATCH_UP_TIP:"MATCH_UP_TIP",//弹出晋级提示
    MATCH_REFRESH_APPLY:"MATCH_REFRESH_APPLY",//刷新报名状态
    MATCH_RECORD_DATA:"MATCH_RECORD_DATA",//刷新比赛场配置界面
    MATCH_REMOVE_WAIT:"MATCH_REMOVE_WAIT",//移除比赛场等待界面
    MATCH_REFRESH_WAIT:"MATCH_REFRESH_WAIT",//刷新等待界面的数据
    REFRESH_TASKGIFT_LIST:"REFRESH_TASKGIFT_LIST",//刷新礼品兑换列表
    REFRESH_ALLGIFT_NUM:"REFRESH_ALLGIFT_NUM",//刷新礼品兑换列表

    //DDZ
    DECIDE_DIZHU:"DECIDE_DIZHU",
    SHOW_FENSHU:"SHOW_FENSHU",
    CLEAN_XIAZHU:"CLEAN_XIAZHU",
    DDZ_STATUS_UPDATE:"DDZ_STATUS_UPDATE",
    FRESH_HANDLES: "FRESH_HANDLES",
    DI_DIZHU_PAI:"DI_DIZHU_PAI",
    UPDATE_BEI_SHU:"UPDATE_BEI_SHU",
    CHUN_TIAN:"CHUN_TIAN",
    REFRESH_HANDLES:"REFRESH_HANDLES",
    SHOW_ZHANKAI:"SHOW_ZHANKAI",


    //新活动
    OPEN_INTIVE_BTN:"OPEN_INTIVE_BTN",
    GET_CASHNUM_BY_ACTIVITY:"GET_CASHNUM_BY_ACTIVITY",
    REFRESH_BY_ACTIVITY:"REFRESH_BY_ACTIVITY",
    GET_OLDERBACK_GIFT:"GET_OLDERBACK_GIFT",
    GET_OLDERBACK_BTN:"GET_OLDERBACK_BTN",
    GET_NEWUSERHASGIFT_GIFT:"GET_NEWUSERHASGIFT_GIFT",
    GET_NEWUSERHASGIFT_BTN:"GET_NEWUSERHASGIFT_BTN",

    //刷新信用的配置
    UPDATA_CREDIT_PARMS:"UPDATA_CREDIT_PARMS",
    UPDATA_CREDIT_NUM:"UPDATA_CREDIT_NUM",
    UPDATA_CREDIT_RATIO:"UPDATA_CREDIT_RATIO",

    UPDATE_MESSAGE_REDPOINT:"UPDATE_MESSAGE_REDPOINT",//刷新被邀请的红点提示

    UPDATE_SHOW_BAGWANFA:"UPDATE_SHOW_BAGWANFA",//刷新被邀请的红点提示

    CLUB_BAG_FASTJOIN:"CLUB_BAG_FASTJOIN",
    CLUB_BAG_CREATE:"CLUB_BAG_CREATE",
    UPDATE_TUOGUAN_TIME:"UPDATE_TUOGUAN_TIME",

    UPDATA_AGENt_PROCE:"UPDATA_AGENt_PROCE",


    //打麻将
    SHOW_HU_CARDS:"SHOW_HU_CARDS",
    HIDE_HU_CARDS:"HIDE_HU_CARDS",
    SHOW_TING_CARDS:"SHOW_TING_CARDS",
    SHOW_DESKTTOP_CARDS:"SHOW_DESKTTOP_CARDS",
    CANCEL_SHOW_DESKTTOP_CARDS:"CANCEL_SHOW_DESKTTOP_CARDS",
    FIND_HU_BY_PUTOUT:"FIND_HU_BY_PUTOUT",
    DAPAI_TING:"DAPAI_TING",

    UPDATA_GOLD_BTN_STATE:"UPDATA_GOLD_BTN_STATE",//刷新金币场按钮状态

    PHZ_CLEAN_SPANEL:"PHZ_CLEAN_SPANEL",//清除跑胡子剩余牌

    SYMJ_JIACHUI:"SYMJ_JIACHUI",//邵阳麻将显示加锤
    SYMJ_JIACHUI_STATE:"SYMJ_JIACHUI_STATE",//邵阳麻将选择加锤

    SOCKET_LOGIN_SUCCESS:"SOCKET_LOGIN_SUCCESS",//长连接登录回调

    PLAY_CARD_AFTER_XIAOHU:"PLAY_CARD_AFTER_XIAOHU",
    PIAO_FEN:"PIAO_FEN",
    SELECT_PIAO_FEN:"SELECT_PIAO_FEN",
    CHANGE_MJ_BG:"CHANGE_MJ_BG",
    CHANGE_MJ_CARDS:"CHANGE_MJ_CARDS",

    UPDATE_SIGNIN_STATE:"UPDATE_SIGNIN_STATE",

    UPDATE_AWARD_STATE:"UPDATE_AWARD_STATE",


    CLUBSCOREWARNING_ADD_USER: "CLUBSCOREWARNING_ADD_USER",//团队预警分数添加成员
    CLUBSCOREWARNING_DELETE_USER: "CLUBSCOREWARNING_DELETE_USER",//团队预警分数删除成员
    CLUBSCOREWARNING_MODIFY_WARNINGSCORE: "CLUBSCOREWARNING_MODIFY_WARNINGSCORE",//修改预警分


    HAS_NEW_ACTIVE: "HAS_NEW_ACTIVE",//有活动
    NEW_ACTIVE_REWARD: "NEW_ACTIVE_REWARD",//领奖状态

}

/**
 * 事件管理分发
 * @type {{addEventListener: Function, removeListener: Function, dispatchEvent: Function}}
 */
var SyEventManager = {
    /**
     * 添加事件监听<br>
     * e.g. var listener = EventUtil.addEventListener(EventType.HIDE_BASE_POP_PANEL, this, this.onClose);
     * @param eventType
     * @param target
     * @param selector
     * @returns listener
     */
    addEventListener:function(eventType,target,selector){
        //监听listview改变事件
        var listener = cc.EventListener.create({
            event: cc.EventListener.CUSTOM,
            eventName: eventType,
            callback: function(event){
                selector.call(target,event);
            }
        });
        cc.eventManager.addListener(listener, target);
        return listener;
    },

    /**
     * 移除事件监听
     * @param listener
     */
    removeListener:function(listener){
        cc.eventManager.removeListener(listener);
    },

    /**
     * 广播分发事件
     * @param eventType
     * @param userData
     */
    dispatchEvent:function(eventType,userData){
        var event = new cc.EventCustom(eventType);
        event.setUserData(userData);
        cc.eventManager.dispatchEvent(event);
    }
}